version: "3"
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: gateway
    ports:
      - 8080:8080
  loyalty:
    build:
      context: .
      dockerfile: loyalty/Dockerfile
    image: loyalty
    ports:
      - 8081:8081
